# Generated by Django 5.0.6 on 2024-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_question_text_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
