# Generated by Django 5.0.6 on 2024-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_is_repeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
