# Generated by Django 5.0.6 on 2024-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
