# Generated by Django 5.0.6 on 2024-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_text_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
