# Generated by Django 5.0.6 on 2024-10-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
