# Generated by Django 5.0.6 on 2024-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
